CREATE TABLE IF NOT EXISTS public.BS_DEMO (
                                              DE_ID NUMERIC(38, 0) NOT NULL,
    DE_UUID VARCHAR(36) NOT NULL,
    DE_DESCRIPTION VARCHAR(50),
    CONSTRAINT BS_DEMO_PK PRIMARY KEY (DE_ID),
    CONSTRAINT BS_DEMO_UN UNIQUE (DE_UUID)
    );