database:
    dbname: database
    host: localhost
    password: l1dEtYRuPSMYfm3r
    port: 5432
    user: username
grpc:
    cert: ./workspace/ssl/server.crt
    client: localhost:9092
    key: ./workspace/ssl/server.pem
    protocol: tcp
    server: localhost:9091
queue:
    consumer: QU-APP-CONSUMER
    producer: QU-APP-PRODUCER
rabbitmq:
    host: localhost
    password: password
    port: 5671
    protocol: amqp
    user: guest
    vhost: guest
scheduler:
    enable: true
server:
    environment: prod
    host: localhost
    logging: info
    name: go
    port: :3000
    timeout: 30
ssh:
    enable: false
    host: localhost
    known_hosts: pkg/adapters/ssh/workspace/docker/keys/known_hosts
    password: cbaciliod
    port: 2222
    private_key: pkg/adapters/ssh/workspace/docker/keys/id_rsa
    protocol: tcp
    public_key: pkg/adapters/ssh/workspace/docker/keys/id_rsa.pub
    username: cbaciliod
