@startuml
'https://plantuml.com/class-diagram


    namespace cmd{}
    namespace pkg{

            namespace adapters{}
          

            namespace components{}
            namespace config{}
            namespace server{}
            namespace task{}
    }


@enduml