// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/adapters/ftp/ftp.go

// Package mock_ftp is a generated GoMock package.
package mock_ftp

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	sftp "github.com/pkg/sftp"
	ssh "golang.org/x/crypto/ssh"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Connection mocks base method.
func (m *MockExecutor) Connection(con *ssh.Client) (*sftp.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connection", con)
	ret0, _ := ret[0].(*sftp.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connection indicates an expected call of Connection.
func (mr *MockExecutorMockRecorder) Connection(con interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connection", reflect.TypeOf((*MockExecutor)(nil).Connection), con)
}

// GetRootPath mocks base method.
func (m *MockExecutor) GetRootPath(conn *sftp.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRootPath", conn)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetRootPath indicates an expected call of GetRootPath.
func (mr *MockExecutorMockRecorder) GetRootPath(conn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRootPath", reflect.TypeOf((*MockExecutor)(nil).GetRootPath), conn)
}
