services:
  postgres-db:
    build:
      context: db
      dockerfile: Dockerfile
    container_name: postgres-db
    env_file:
      - db/.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - ssh-net

networks:
  ssh-net:
    name: ssh-net
    driver: bridge

